// ===== Export Menu =====

function toggleExportMenu(e) {
    e.stopPropagation();
    var menu = document.getElementById('exportMenu');
    menu.classList.toggle('active');
}

function closeExportMenu() {
    var menu = document.getElementById('exportMenu');
    if (menu) menu.classList.remove('active');
}

// Close export menu when clicking outside
document.addEventListener('click', function (e) {
    var dropdown = document.getElementById('exportDropdown');
    if (dropdown && !dropdown.contains(e.target)) {
        closeExportMenu();
    }
});

function getExportRequests() {
    // If there are selected rows, export those; otherwise export all filtered
    if (selectedRows && selectedRows.size > 0) {
        return filteredRequests.filter(function (r) { return selectedRows.has(String(r.id)); });
    }
    return filteredRequests;
}

// ===== cURL Export =====

function escapeShellArg(str) {
    return "'" + str.replace(/'/g, "'\\''") + "'";
}

function exportCurlScript() {
    var reqs = getExportRequests();
    if (!reqs || reqs.length === 0) {
        alert('No requests to export.');
        return;
    }

    var lines = ['#!/bin/bash', '# Generated by HAR-Viewer', '# ' + reqs.length + ' request(s)', ''];

    reqs.forEach(function (req, i) {
        lines.push('# Request ' + (i + 1) + ': ' + req.method + ' ' + req.uri);
        var cmd = 'curl -X ' + req.method;

        // Add request headers
        var headers = req.requestHeaders;
        if (headers && typeof headers === 'object') {
            Object.keys(headers).forEach(function (key) {
                cmd += ' \\\n  -H ' + escapeShellArg(key + ': ' + headers[key]);
            });
        } else if (headers && typeof headers === 'string') {
            headers.split('\n').forEach(function (line) {
                line = line.trim();
                if (line) cmd += ' \\\n  -H ' + escapeShellArg(line);
            });
        }

        // Add request body
        var body = null;
        if (req.requestBodyChunks && req.requestBodyChunks.length > 0) {
            body = req.requestBodyChunks.join('');
        }
        if (body) {
            cmd += ' \\\n  -d ' + escapeShellArg(body);
        }

        cmd += ' \\\n  ' + escapeShellArg(req.uri);
        lines.push(cmd);
        lines.push('');
    });

    var blob = new Blob([lines.join('\n')], { type: 'text/x-shellscript' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'requests_' + new Date().toISOString().slice(0, 10) + '.sh';
    a.click();
    URL.revokeObjectURL(url);
}

// ===== Postman Collection Export =====

function exportPostmanCollection() {
    var reqs = getExportRequests();
    if (!reqs || reqs.length === 0) {
        alert('No requests to export.');
        return;
    }

    var items = reqs.map(function (req) {
        // Parse URL
        var urlObj = null;
        try { urlObj = new URL(req.uri); } catch (e) { }

        // Build headers array
        var headerList = [];
        var headers = req.requestHeaders;
        if (headers && typeof headers === 'object') {
            Object.keys(headers).forEach(function (key) {
                headerList.push({ key: key, value: String(headers[key]) });
            });
        } else if (headers && typeof headers === 'string') {
            headers.split('\n').forEach(function (line) {
                line = line.trim();
                if (!line) return;
                var idx = line.indexOf(':');
                if (idx > 0) {
                    headerList.push({ key: line.substring(0, idx).trim(), value: line.substring(idx + 1).trim() });
                }
            });
        }

        // Build body
        var body = null;
        var bodyContent = null;
        if (req.requestBodyChunks && req.requestBodyChunks.length > 0) {
            bodyContent = req.requestBodyChunks.join('');
        }
        if (bodyContent) {
            // Detect content type for mode
            var ct = '';
            headerList.forEach(function (h) { if (h.key.toLowerCase() === 'content-type') ct = h.value.toLowerCase(); });
            var mode = 'raw';
            var options = { raw: { language: 'text' } };
            if (ct.indexOf('json') !== -1) {
                options.raw.language = 'json';
            } else if (ct.indexOf('xml') !== -1) {
                options.raw.language = 'xml';
            } else if (ct.indexOf('html') !== -1) {
                options.raw.language = 'html';
            }
            body = { mode: mode, raw: bodyContent, options: options };
        }

        // Build URL object for Postman
        var urlSpec = { raw: req.uri };
        if (urlObj) {
            urlSpec.protocol = urlObj.protocol.replace(':', '');
            urlSpec.host = urlObj.hostname.split('.');
            if (urlObj.port) urlSpec.port = urlObj.port;
            urlSpec.path = urlObj.pathname.split('/').filter(function (p) { return p; });
            if (urlObj.search) {
                urlSpec.query = [];
                urlObj.searchParams.forEach(function (v, k) {
                    urlSpec.query.push({ key: k, value: v });
                });
            }
        }

        var item = {
            name: req.method + ' ' + (urlObj ? urlObj.pathname : req.uri),
            request: {
                method: req.method,
                header: headerList,
                url: urlSpec
            }
        };
        if (body) item.request.body = body;

        // Add response example
        var resHeaders = [];
        var rh = req.responseHeaders;
        if (rh && typeof rh === 'object') {
            Object.keys(rh).forEach(function (key) {
                resHeaders.push({ key: key, value: String(rh[key]) });
            });
        }
        var resBody = '';
        if (req.responseBodyChunks && req.responseBodyChunks.length > 0) {
            resBody = req.responseBodyChunks.join('');
        }
        item.response = [{
            name: req.method + ' ' + (urlObj ? urlObj.pathname : req.uri),
            originalRequest: item.request,
            status: (req.msg || 'OK'),
            code: req.status,
            header: resHeaders,
            body: resBody
        }];

        return item;
    });

    var collection = {
        info: {
            name: 'HAR-Viewer Export (' + new Date().toISOString().slice(0, 10) + ')',
            schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
            description: 'Exported from HAR-Viewer. ' + items.length + ' request(s).'
        },
        item: items
    };

    var blob = new Blob([JSON.stringify(collection, null, 2)], { type: 'application/json' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'postman_collection_' + new Date().toISOString().slice(0, 10) + '.json';
    a.click();
    URL.revokeObjectURL(url);
}
