function shellEscape(value) {
    return "'" + String(value || '').replace(/'/g, "'\\''") + "'";
}

function getRequestsForReplayScope(scope) {
    if (scope === 'selected' && selectedRows.size > 0) {
        return filteredRequests.filter(function(request) {
            return selectedRows.has(String(request.id));
        });
    }
    return filteredRequests.slice();
}

function buildCurlCommand(request) {
    let command = 'curl';
    if (request.method && request.method !== 'GET') {
        command += ' -X ' + request.method;
    }

    const headers = normalizeHeaderMap(request.requestHeaders);
    Object.keys(headers).forEach(function(key) {
        command += ' \\\n  -H ' + shellEscape(key + ': ' + headers[key]);
    });

    const requestBody = request.requestBodyText || (request.requestBodyChunks || []).join('');
    if (requestBody) {
        command += ' \\\n  --data-raw ' + shellEscape(requestBody);
    }

    command += ' \\\n  ' + shellEscape(request.uri);
    return command;
}

function buildReplayModel(request) {
    return {
        id: request.id,
        method: request.method,
        url: request.uri,
        requestHeaders: normalizeHeaderMap(request.requestHeaders),
        requestBody: request.requestBodyText || (request.requestBodyChunks || []).join(''),
        responseStatus: request.status,
        responseHeaders: normalizeHeaderMap(request.responseHeaders),
        responseBody: request.responseOriginalBody || request.responseBodyText || (request.responseBodyChunks || []).join(''),
        responseMimeType: request.responseMimeType || getHeaderValue(request.responseHeaders, 'Content-Type') || ''
    };
}

function downloadTextFile(fileName, content, mimeType) {
    const blob = new Blob([content], { type: mimeType || 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
}

function buildPostmanCollection(requests, name) {
    return {
        info: {
            name: name,
            schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
        },
        item: requests.map(function(request) {
            const model = buildReplayModel(request);
            return {
                name: request.method + ' ' + (request.path || request.uri),
                request: {
                    method: model.method,
                    header: Object.keys(model.requestHeaders).map(function(key) {
                        return { key: key, value: model.requestHeaders[key] };
                    }),
                    body: model.requestBody ? { mode: 'raw', raw: model.requestBody } : undefined,
                    url: model.url
                }
            };
        })
    };
}

function buildMockBundle(requests) {
    const files = [];
    const routes = [];
    requests.forEach(function(request) {
        const model = buildReplayModel(request);
        const extension = model.responseMimeType.indexOf('json') !== -1 ? 'json' : 'txt';
        const bodyFile = 'responses/' + request.id + '.' + extension;
        routes.push({
            id: request.id,
            method: model.method,
            matcher: request.requestKeyWithoutQuery,
            status: model.responseStatus,
            headers: model.responseHeaders,
            bodyFile: bodyFile,
            responseMimeType: model.responseMimeType
        });
        files.push({ name: bodyFile, content: model.responseBody || '' });
    });
    files.push({ name: 'mock-routes.json', content: JSON.stringify(routes, null, 2) });
    files.push({ name: 'README.txt', content: 'Mock bundle generated by HAR-Viewer. Routes are listed in mock-routes.json and response payloads live under responses/.' });
    return files;
}

function openReplayExportDialog() {
    const dialog = document.getElementById('replayExportBackdrop');
    const scopeSelected = document.getElementById('replayScopeSelected');
    const info = document.getElementById('replayScopeInfo');
    const selectedCount = selectedRows.size;
    const totalCount = filteredRequests.length;

    scopeSelected.disabled = selectedCount === 0;
    if (selectedCount === 0) {
        document.querySelector('input[name="replayScope"][value="filtered"]').checked = true;
    }

    info.textContent = selectedCount > 0
        ? (selectedCount + ' selected requests, ' + totalCount + ' filtered total.')
        : (totalCount + ' filtered requests available. Select rows to export a subset.');

    dialog.classList.add('active');
}

function closeReplayExportDialog(event) {
    if (event && event.target !== document.getElementById('replayExportBackdrop')) {
        return;
    }
    document.getElementById('replayExportBackdrop').classList.remove('active');
}

function executeReplayExport() {
    const format = document.getElementById('replayFormat').value;
    const scope = document.querySelector('input[name="replayScope"]:checked').value;
    const requests = getRequestsForReplayScope(scope);
    if (!requests.length) {
        showError('No requests available for replay export.');
        return;
    }

    if (format === 'curl') {
        const script = requests.map(function(request) {
            return buildCurlCommand(request);
        }).join('\n\n');
        downloadTextFile(requests.length === 1 ? ('request_' + requests[0].id + '.sh') : 'requests.sh', script, 'text/x-shellscript;charset=utf-8');
        if (requests.length === 1) {
            navigator.clipboard.writeText(script);
        }
    } else if (format === 'postman') {
        const activeDataset = getActiveDataset();
        const collection = buildPostmanCollection(requests, (activeDataset && (activeDataset.metadata.sourceLabel || activeDataset.metadata.sourceName)) || 'HAR-Viewer Export');
        downloadTextFile('postman_collection.json', JSON.stringify(collection, null, 2), 'application/json;charset=utf-8');
    } else if (format === 'mock') {
        const files = buildMockBundle(requests);
        downloadAsZip(files, 'mock_bundle.zip');
    }

    closeReplayExportDialog();
}
